#version 430
layout(local_size_x = 8, local_size_y = 8) in;
layout(std430, binding = 0) buffer pixelVec { vec4 pixel[]; };
uniform vec2 viewSize;
uniform int currentFrame;

void main()
{
    uvec2 view = uvec2(viewSize);
    if (view.x > gl_GlobalInvocationID.x && view.y > gl_GlobalInvocationID.y)
        pixel[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * view.x] = vec4(vec2(gl_GlobalInvocationID.xy) / viewSize, 0.5f + 0.4 * sin(0.001f * currentFrame), 1.0);
}
